name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: clean
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: bootWar --scan
    - name: Copy war to Root
      run: mv ./build/libs/*.war ./ROOT.war
    - name: Copy file And deploy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "ROOT.war"
        target: "~/tomcat/webapps"